# Generated by Django 5.0.3 on 2024-04-17 00:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Freestyle', 'Freestyle'), ('All-Mountain', 'All-Mountain'), ('Freeride', 'Freeride'), ('Powder', 'Powder')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snowboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='Unknown', max_length=20)),
                ('shape', models.CharField(choices=[('Directional', 'Directional'), ('Directional Twin', 'Directional Twin'), ('Tapered Directional', 'Tapered Directional'), ('True Twin', 'True Twin'), ('Twin', 'Twin')], default='Directional', max_length=20)),
                ('profile', models.CharField(choices=[('Flat', 'Flat'), ('Camber', 'Camber'), ('Rocker', 'Rocker'), ('Hybrid Camber', 'Hybrid Camber'), ('Hybrid Rocker', 'Hybrid Rocker')], default='Flat', max_length=20)),
                ('rider', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=20)),
                ('flex', models.IntegerField(default=0)),
                ('brand', models.CharField(default='Unknown', max_length=20)),
                ('name', models.CharField(default='Unknown', max_length=50)),
                ('desc', models.CharField(default='No description available', max_length=500)),
                ('image', models.ImageField(default='snowboards/blank.jpg', null=True, upload_to='snowboards/')),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('sizes', models.ManyToManyField(to='snowReview.size')),
                ('terrain', models.ManyToManyField(to='snowReview.terrain')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snow24', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('snow7', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('boardSize', models.CharField(choices=[('130', '130 cm'), ('131', '131 cm'), ('132', '132 cm'), ('133', '133 cm'), ('134', '134 cm'), ('135', '135 cm'), ('136', '136 cm'), ('137', '137 cm'), ('138', '138 cm'), ('139', '139 cm'), ('140', '140 cm'), ('141', '141 cm'), ('142', '142 cm'), ('143', '143 cm'), ('144', '144 cm'), ('145', '145 cm'), ('146', '146 cm'), ('147', '147 cm'), ('148', '148 cm'), ('149', '149 cm'), ('150', '150 cm'), ('151', '151 cm'), ('152', '152 cm'), ('153', '153 cm'), ('154', '154 cm'), ('155', '155 cm'), ('156', '156 cm'), ('157', '157 cm'), ('158', '158 cm'), ('159', '159 cm'), ('160', '160 cm'), ('161', '161 cm'), ('162', '162 cm'), ('163', '163 cm'), ('164', '164 cm'), ('165', '165 cm'), ('166', '166 cm'), ('167', '167 cm'), ('168', '168 cm'), ('169', '169 cm')], default='130', max_length=200)),
                ('date', models.DateField(default='2024-01-01')),
                ('conditions', models.CharField(default='Describe Conditions', max_length=200)),
                ('riderHeight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('riderWeight', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowReview.profile')),
                ('snowboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowReview.snowboard')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='Add text here', validators=[django.core.validators.MaxLengthValidator(200)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snowboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowReview.snowboard')),
            ],
        ),
    ]
