# Generated by Django 5.0.3 on 2024-03-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowboard',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='brands/'),
        ),
        migrations.AddField(
            model_name='snowboard',
            name='image',
            field=models.ImageField(null=True, upload_to='snowboards/'),
        ),
    ]
