# Generated by Django 5.0.3 on 2024-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.BooleanField(null=True),
        ),
    ]
