# Generated by Django 5.0.3 on 2024-03-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0002_snowboard_brand_image_snowboard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snowboard',
            name='price',
        ),
    ]
