# Generated by Django 5.0.3 on 2024-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0003_remove_snowboard_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Freestyle', 'Freestyle'), ('All-Mountain', 'All-Mountain'), ('Freeride', 'Freeride'), ('Powder', 'Powder')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='snowboard',
            name='terrain',
            field=models.ManyToManyField(to='snowReview.terrain'),
        ),
    ]
