# Generated by Django 5.0.3 on 2024-04-19 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0003_alter_vote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowReview.comment'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snowReview.review'),
        ),
    ]
