# Generated by Django 5.0.3 on 2024-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0004_alter_vote_comment_alter_vote_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='brand',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='profile',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Camber', 'Camber'), ('Rocker', 'Rocker'), ('Hybrid Camber', 'Hybrid Camber'), ('Hybrid Rocker', 'Hybrid Rocker')], default='Flat', max_length=40),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='rider',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=40),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='season',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='shape',
            field=models.CharField(choices=[('Directional', 'Directional'), ('Directional Twin', 'Directional Twin'), ('Tapered Directional', 'Tapered Directional'), ('True Twin', 'True Twin'), ('Twin', 'Twin')], default='Directional', max_length=40),
        ),
    ]
