# Generated by Django 5.0.3 on 2024-07-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0005_alter_snowboard_brand_alter_snowboard_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='season',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
