# Generated by Django 5.0.3 on 2024-03-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0005_alter_snowboard_desc_alter_terrain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
