# Generated by Django 5.0.3 on 2024-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0006_alter_snowboard_brand_alter_snowboard_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
