# Generated by Django 5.0.3 on 2024-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0008_size_snowboard_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
