# Generated by Django 5.0.3 on 2024-03-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0011_remove_comment_profile_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='riderHeight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
