# Generated by Django 5.0.3 on 2024-04-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0012_alter_review_riderheight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='media/brands'),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='image',
            field=models.ImageField(null=True, upload_to='media/snowboards'),
        ),
    ]
