# Generated by Django 5.0.3 on 2024-04-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0013_alter_snowboard_brand_image_alter_snowboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='image',
            field=models.ImageField(null=True, upload_to='snowboards/'),
        ),
    ]
