# Generated by Django 5.0.3 on 2024-04-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0014_alter_snowboard_brand_image_alter_snowboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='riderHeight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
