# Generated by Django 5.0.3 on 2024-04-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0015_alter_review_riderheight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='riderHeight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='snowboard',
            name='image',
            field=models.ImageField(default='snowboards/default.jpg', null=True, upload_to='snowboards/'),
        ),
    ]
