# Generated by Django 5.0.3 on 2024-04-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0016_alter_review_riderheight_alter_snowboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowboard',
            name='brand_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
    ]
