# Generated by Django 5.0.3 on 2024-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0018_review_updated_at_alter_snowboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
