# Generated by Django 5.0.3 on 2024-04-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0019_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='snow24',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='review',
            name='snow7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
