# Generated by Django 5.0.3 on 2024-04-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0019_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='riderHeight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
