# Generated by Django 5.0.3 on 2024-04-11 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0020_alter_review_snow24_alter_review_snow7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='snow24',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='snow7',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
