# Generated by Django 5.0.3 on 2024-04-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowReview', '0021_alter_review_snow24_alter_review_snow7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='riderHeight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
